version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    # image: halloegar/node-app # for pulling from dockerhub
    # ports: # disable when using nginx
    #   - '3000:3000' # disable when using nginx
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.3
    volumes:
      - mongo-db:/data/db
    # ports:
    #   - '27017:27017'

  redis:
    image: redis:7.0.6

volumes:
  mongo-db:
