version: '3'
services:
  nginx:
    ports:
      - '3000:80'

  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro # sync volume
      - /app/node_modules # anonymous volume
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=password
      - SESSION_SECRET=secret
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
